import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'

const isDev = process.env["DFX_NETWORK"] !== "ic"
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    // alias: {
    //   '@astrox/sdk-web': resolve('../../packages/web/src/'),
    //   '@astrox/sdk-core': resolve('../../packages/core/src/'),
    // }
  },
  define: {
    // Here we can define global constants
    // This is required for now because the code generated by dfx relies on process.env being set
    "process.env.NODE_ENV": JSON.stringify(
      isDev ? "development" : "production",
    ),
  },
})
